image: /home/adrianb3/catkin_ws/src/hide_and_seek/hide_and_seek_navigation/config/map.pgm
resolution: 0.050000
origin: [-10.000000, -10.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

